// Generated by gencpp from file ser/op.msg
// DO NOT EDIT!


#ifndef SER_MESSAGE_OP_H
#define SER_MESSAGE_OP_H

#include <ros/service_traits.h>


#include <ser/opRequest.h>
#include <ser/opResponse.h>


namespace ser
{

struct op
{

typedef opRequest Request;
typedef opResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct op
} // namespace ser


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ser::op > {
  static const char* value()
  {
    return "4781436a0c2affec8025955a6041e481";
  }

  static const char* value(const ::ser::op&) { return value(); }
};

template<>
struct DataType< ::ser::op > {
  static const char* value()
  {
    return "ser/op";
  }

  static const char* value(const ::ser::op&) { return value(); }
};


// service_traits::MD5Sum< ::ser::opRequest> should match
// service_traits::MD5Sum< ::ser::op >
template<>
struct MD5Sum< ::ser::opRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ser::op >::value();
  }
  static const char* value(const ::ser::opRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ser::opRequest> should match
// service_traits::DataType< ::ser::op >
template<>
struct DataType< ::ser::opRequest>
{
  static const char* value()
  {
    return DataType< ::ser::op >::value();
  }
  static const char* value(const ::ser::opRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ser::opResponse> should match
// service_traits::MD5Sum< ::ser::op >
template<>
struct MD5Sum< ::ser::opResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ser::op >::value();
  }
  static const char* value(const ::ser::opResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ser::opResponse> should match
// service_traits::DataType< ::ser::op >
template<>
struct DataType< ::ser::opResponse>
{
  static const char* value()
  {
    return DataType< ::ser::op >::value();
  }
  static const char* value(const ::ser::opResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SER_MESSAGE_OP_H
