// Generated by gencpp from file ser/opResponse.msg
// DO NOT EDIT!


#ifndef SER_MESSAGE_OPRESPONSE_H
#define SER_MESSAGE_OPRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ser
{
template <class ContainerAllocator>
struct opResponse_
{
  typedef opResponse_<ContainerAllocator> Type;

  opResponse_()
    : sum(0)  {
    }
  opResponse_(const ContainerAllocator& _alloc)
    : sum(0)  {
  (void)_alloc;
    }



   typedef int32_t _sum_type;
  _sum_type sum;





  typedef boost::shared_ptr< ::ser::opResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ser::opResponse_<ContainerAllocator> const> ConstPtr;

}; // struct opResponse_

typedef ::ser::opResponse_<std::allocator<void> > opResponse;

typedef boost::shared_ptr< ::ser::opResponse > opResponsePtr;
typedef boost::shared_ptr< ::ser::opResponse const> opResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ser::opResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ser::opResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ser::opResponse_<ContainerAllocator1> & lhs, const ::ser::opResponse_<ContainerAllocator2> & rhs)
{
  return lhs.sum == rhs.sum;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ser::opResponse_<ContainerAllocator1> & lhs, const ::ser::opResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ser

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ser::opResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ser::opResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ser::opResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ser::opResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ser::opResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ser::opResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ser::opResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0ba699c25c9418c0366f3595c0c8e8ec";
  }

  static const char* value(const ::ser::opResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0ba699c25c9418c0ULL;
  static const uint64_t static_value2 = 0x366f3595c0c8e8ecULL;
};

template<class ContainerAllocator>
struct DataType< ::ser::opResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ser/opResponse";
  }

  static const char* value(const ::ser::opResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ser::opResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# 服务器响应发送的数据\n"
"int32 sum\n"
"\n"
;
  }

  static const char* value(const ::ser::opResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ser::opResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.sum);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct opResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ser::opResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ser::opResponse_<ContainerAllocator>& v)
  {
    s << indent << "sum: ";
    Printer<int32_t>::stream(s, indent + "  ", v.sum);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SER_MESSAGE_OPRESPONSE_H
