// Generated by gencpp from file up/addFeedback.msg
// DO NOT EDIT!


#ifndef UP_MESSAGE_ADDFEEDBACK_H
#define UP_MESSAGE_ADDFEEDBACK_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace up
{
template <class ContainerAllocator>
struct addFeedback_
{
  typedef addFeedback_<ContainerAllocator> Type;

  addFeedback_()
    : progress_bar(0.0)  {
    }
  addFeedback_(const ContainerAllocator& _alloc)
    : progress_bar(0.0)  {
  (void)_alloc;
    }



   typedef double _progress_bar_type;
  _progress_bar_type progress_bar;





  typedef boost::shared_ptr< ::up::addFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::up::addFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct addFeedback_

typedef ::up::addFeedback_<std::allocator<void> > addFeedback;

typedef boost::shared_ptr< ::up::addFeedback > addFeedbackPtr;
typedef boost::shared_ptr< ::up::addFeedback const> addFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::up::addFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::up::addFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::up::addFeedback_<ContainerAllocator1> & lhs, const ::up::addFeedback_<ContainerAllocator2> & rhs)
{
  return lhs.progress_bar == rhs.progress_bar;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::up::addFeedback_<ContainerAllocator1> & lhs, const ::up::addFeedback_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace up

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::up::addFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::up::addFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::up::addFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::up::addFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::up::addFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::up::addFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::up::addFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ac7532a8a8f0d2be4f5284d94fee2d59";
  }

  static const char* value(const ::up::addFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xac7532a8a8f0d2beULL;
  static const uint64_t static_value2 = 0x4f5284d94fee2d59ULL;
};

template<class ContainerAllocator>
struct DataType< ::up::addFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "up/addFeedback";
  }

  static const char* value(const ::up::addFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::up::addFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"#连续反馈\n"
"float64 progress_bar\n"
"\n"
;
  }

  static const char* value(const ::up::addFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::up::addFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.progress_bar);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct addFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::up::addFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::up::addFeedback_<ContainerAllocator>& v)
  {
    s << indent << "progress_bar: ";
    Printer<double>::stream(s, indent + "  ", v.progress_bar);
  }
};

} // namespace message_operations
} // namespace ros

#endif // UP_MESSAGE_ADDFEEDBACK_H
